sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install coverage detox tox-travis

script:
  - coverage erase
  - detox

after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov

matrix:
  include:
    - python: "3.6"
      env: TOXENV="warnings"
  allow_failures:
    - env: TOXENV="warnings"
    - env: TOXENV="py35-djangolatest-restframeworklatest"
    - env: TOXENV="py36-djangolatest-restframeworklatest"

