sudo: false

language: python
python: "3.5"

cache: pip

install:
  - pip install coverage detox

script:
  - coverage erase
  - detox

after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov

